# -*- coding: utf-8 -*-
"""duckdb_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14uja_F3_-1KY5O2pSjIXStSlCJ_V2E7z
"""

pip install pyspark

def set_active_pyspark():
  '''Ativa o framework pyspark no Google Colab'''
  from pyspark.sql import SparkSession
  spark = SparkSession.builder.appName("scrap_page").enableHiveSupport().master("local").getOrCreate()
  return spark

spark = set_active_pyspark()

"""____
## Installing DuckDB
"""

pip install duckdb --upgrade

import duckdb

cursor = duckdb.connect()
print(cursor.execute('SELECT 42').fetchall())

duckdb.sql('''CREATE TABLE cities (
    name VARCHAR,
    lat  DECIMAL,
    lon  DECIMAL
);''')

v_query = '''
INSERT INTO cities
VALUES ('San Francisco', -194.0, 53.0);
'''
duckdb.sql(v_query)

v_query = '''
INSERT INTO weather
VALUES ('San Francisco', 46, 50, 0.25, '1994-11-27');
'''
duckdb.sql(v_query)

v_query = '''
INSERT INTO weather (city, temp_lo, temp_hi, prcp, date)
VALUES ('San Francisco', 43, 57, 0.0, '1994-11-29');
'''
duckdb.sql(v_query)

v_query = '''
INSERT INTO weather (date, city, temp_hi, temp_lo)
VALUES ('1994-11-29', 'Hayward', 54, 37);
'''
duckdb.sql(v_query)

v_query = '''
SELECT *
FROM weather;
'''
duckdb.sql(v_query)

v_query = '''
SELECT city, (temp_hi + temp_lo) / 2 AS temp_avg, date
FROM weather;
'''
duckdb.sql(v_query)

v_query = '''
SELECT *
FROM weather
WHERE city = 'San Francisco' AND prcp > 0.0;
'''
duckdb.sql(v_query)

duckdb.sql('describe weather')

duckdb.sql('describe cities')

v_query = '''
SELECT *
FROM weather, cities
WHERE city = name;
'''
duckdb.sql(v_query)

# fetchall() generate a list as result
v_query = '''
SELECT *
FROM weather, cities
WHERE city = name;
'''
results = duckdb.sql(v_query).fetchall()

type(results)

results

# to_df() generate result as Pandas dataframe
v_query = '''
SELECT *
FROM weather, cities
WHERE city = name;
'''
results_2 = duckdb.sql(v_query).to_df()

type(results_2)

results_2