#!/usr/bin/env python
# coding: utf-8

import os
import shutil
from zipfile import ZipFile

v_file = '/dbfs/mnt/my_path/files_ziped.zip'
output_dir = '/dbfs/mnt/sandbox/output_zip'

# Create the output directory if it does not exist
os.makedirs(output_dir, exist_ok=True)

with ZipFile(v_file, 'r') as ZipObj:
    for member in ZipObj.namelist():
        with ZipObj.open(member) as source, open(f'{output_dir}/{member}', 'wb') as target:
            shutil.copyfileobj(source, target, length=1024*1024*10)  # 10 MB buffer size
